// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANIdyNIVCV_LXsUjxTUcND1a6-jtxnRNI',
    appId: '1:122070373045:web:26825964a73d40af5764fc',
    messagingSenderId: '122070373045',
    projectId: 'sc2006-8e836',
    authDomain: 'sc2006-8e836.firebaseapp.com',
    storageBucket: 'sc2006-8e836.appspot.com',
    measurementId: 'G-DJ9C6TXYYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOjFK99fwIgmGyW6B7zhhsxVRzWAorhmA',
    appId: '1:122070373045:android:206401a496a8eaed5764fc',
    messagingSenderId: '122070373045',
    projectId: 'sc2006-8e836',
    storageBucket: 'sc2006-8e836.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCtkcmXS6soZ5NAK6zgo1ebhhzDzdlRkI',
    appId: '1:122070373045:ios:ffb70b9a140e779b5764fc',
    messagingSenderId: '122070373045',
    projectId: 'sc2006-8e836',
    storageBucket: 'sc2006-8e836.appspot.com',
    iosClientId: '122070373045-v6pr1mklohtuvuhrpuir4n279j2fdaut.apps.googleusercontent.com',
    iosBundleId: 'com.example.busAwayFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCtkcmXS6soZ5NAK6zgo1ebhhzDzdlRkI',
    appId: '1:122070373045:ios:ffb70b9a140e779b5764fc',
    messagingSenderId: '122070373045',
    projectId: 'sc2006-8e836',
    storageBucket: 'sc2006-8e836.appspot.com',
    iosClientId: '122070373045-v6pr1mklohtuvuhrpuir4n279j2fdaut.apps.googleusercontent.com',
    iosBundleId: 'com.example.busAwayFirestore',
  );
}
